const N={K:'王',R:'飛',B:'角',G:'金',S:'銀',N:'桂',L:'香',P:'歩'},PN={R:'竜',B:'馬',S:'全',N:'圭',L:'杏',P:'と'},V={K:500,R:10,B:9,G:6,S:5,N:3,L:3,P:1};
const SPRITE={P:'s00',L:'s01',N:'s02',S:'s03',G:'s10',B:'s11',R:'s12',K:'s13','+P':'s20','+L':'s21','+N':'s22','+S':'s23','+B':'s30','+R':'s31'};
const LEVELS={
  beginner:{name:'初心者',engine:'legacy',depth:1,beam:30,root:40,time:350,randomness:.8},
  intermediate:{name:'中級者',engine:'legacy',depth:3,beam:8,root:24,time:900,randomness:.35},
  advanced:{name:'上級者',engine:'strong',maxDepth:8,time:2800,qDepth:2,extensions:1,lmr:1,randomness:0},
  master:{name:'猛者',engine:'strong',maxDepth:12,time:6000,qDepth:4,extensions:2,lmr:2,mateDepth:7,mateTime:900,randomness:0},
  hero:{name:'勇者',engine:'yaneuraou',time:2200,randomness:0}
};
const boardEl=$('#board'),statusEl=$('#status'),thinkingEl=$('#thinking'),promotion=$('#promotion');
const dirs={K:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]],G:[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,0]],S:[[-1,-1],[-1,0],[-1,1],[1,-1],[1,1]],N:[[-2,-1],[-2,1]],P:[[-1,0]]};
const goldLike=new Set(['G','S','N','L','P']);
let state,selected=null,legalTargets=[],history=[],records=[],busy=false,level='intermediate',searchNodes=0,completedDepth=0,gameId=0;
let heroWorker=null,heroReady=null,heroReadyResolve=null,heroReadyReject=null,heroSequence=0;
const heroPending=new Map(),transpositionTable=new Map(),SEARCH_TIMEOUT=Symbol('search-timeout'),MATE_SCORE=1000000;
function $(s){return document.querySelector(s)}
function fresh(){const rows=[['L','N','S','G','K','G','S','N','L'],[null,'R',null,null,null,null,null,'B',null],['P','P','P','P','P','P','P','P','P'],...Array.from({length:3},()=>Array(9).fill(null)),['P','P','P','P','P','P','P','P','P'],[null,'B',null,null,null,null,null,'R',null],['L','N','S','G','K','G','S','N','L']];return{board:rows.map((row,r)=>row.map(type=>type?{type,side:r<3?'gote':'sente',promoted:false}:null)),hands:{sente:[],gote:[]},turn:'sente',last:null,winner:null,endReason:null,move:0}}
function clone(s){return{board:s.board.map(row=>row.map(p=>p&&{...p})),hands:{sente:[...s.hands.sente],gote:[...s.hands.gote]},turn:s.turn,last:s.last&&{from:s.last.from&&[...s.last.from],to:[...s.last.to]},winner:s.winner,endReason:s.endReason,move:s.move}}
function inside(r,c){return r>=0&&r<9&&c>=0&&c<9}function other(s){return s==='sente'?'gote':'sente'}function orient(side,d){return side==='sente'?d:[-d[0],-d[1]]}
function pseudoMoves(s,r,c,attackOnly=false){const p=s.board[r][c];if(!p)return[];const out=[],add=(rr,cc)=>{if(!inside(rr,cc))return false;const q=s.board[rr][cc];if(!q||q.side!==p.side)out.push([rr,cc]);return !q};let steps;
  if(p.promoted&&goldLike.has(p.type))steps=dirs.G;else if(p.type==='K')steps=dirs.K;else if(p.type==='G')steps=dirs.G;else if(p.type==='S')steps=dirs.S;else if(p.type==='N')steps=dirs.N;else if(p.type==='P')steps=dirs.P;
  if(steps)for(const d of steps){const [dr,dc]=orient(p.side,d);add(r+dr,c+dc)}
  if(p.promoted&&p.type==='B')for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]])add(r+dr,c+dc);
  if(p.promoted&&p.type==='R')for(const [dr,dc] of [[-1,-1],[-1,1],[1,-1],[1,1]])add(r+dr,c+dc);
  const slide=[];if(p.type==='R')slide.push([-1,0],[1,0],[0,-1],[0,1]);if(p.type==='B')slide.push([-1,-1],[-1,1],[1,-1],[1,1]);if(p.type==='L'&&!p.promoted)slide.push(orient(p.side,[-1,0]));
  for(const [dr,dc] of slide)for(let n=1;n<9;n++)if(!add(r+dr*n,c+dc*n))break;return out}
function attacked(s,r,c,by){for(let rr=0;rr<9;rr++)for(let cc=0;cc<9;cc++){const p=s.board[rr][cc];if(p?.side===by&&pseudoMoves(s,rr,cc,true).some(x=>x[0]===r&&x[1]===c))return true}return false}
function inCheck(s,side){for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(s.board[r][c]?.side===side&&s.board[r][c].type==='K')return attacked(s,r,c,other(side));return true}
function promotionPossible(p,fr,tr){if(p.type==='K'||p.type==='G'||p.promoted)return false;return p.side==='sente'?(fr<=2||tr<=2):(fr>=6||tr>=6)}
function forcedPromotion(p,tr){if(p.promoted)return false;return(p.type==='P'||p.type==='L')&&(p.side==='sente'?tr===0:tr===8)||p.type==='N'&&(p.side==='sente'?tr<=1:tr>=7)}
function apply(s,m){const n=clone(s);if(m.drop){const i=n.hands[m.side].indexOf(m.type);if(i<0)return n;n.hands[m.side].splice(i,1);n.board[m.to[0]][m.to[1]]={type:m.type,side:m.side,promoted:false}}else{const p=n.board[m.from[0]][m.from[1]],cap=n.board[m.to[0]][m.to[1]];n.board[m.from[0]][m.from[1]]=null;if(cap)n.hands[m.side].push(cap.type);n.board[m.to[0]][m.to[1]]={...p,promoted:p.promoted||m.promote}}n.last={from:m.from||null,to:m.to};n.turn=other(m.side);n.move++;return n}
function rawMoves(s,side){const out=[];for(let r=0;r<9;r++)for(let c=0;c<9;c++){const p=s.board[r][c];if(p?.side!==side)continue;for(const to of pseudoMoves(s,r,c)){const pp=promotionPossible(p,r,to[0]),forced=forcedPromotion(p,to[0]);out.push({side,from:[r,c],to,promote:forced});if(pp&&!forced)out.push({side,from:[r,c],to,promote:true})}}
  for(const type of new Set(s.hands[side]))for(let r=0;r<9;r++)for(let c=0;c<9;c++){if(s.board[r][c])continue;if((type==='P'||type==='L')&&(side==='sente'?r===0:r===8))continue;if(type==='N'&&(side==='sente'?r<=1:r>=7))continue;if(type==='P'&&s.board.some(row=>row[c]?.side===side&&row[c].type==='P'&&!row[c].promoted))continue;out.push({side,drop:true,type,to:[r,c]})}return out}
function isPawnDropMate(s,m){if(!m.drop||m.type!=='P')return false;const n=apply(s,m),foe=other(m.side);return inCheck(n,foe)&&legalMoves(n,foe,false).length===0}
function legalMoves(s,side=s.turn,checkPawnMate=true){return rawMoves(s,side).filter(m=>!inCheck(apply(s,m),side)&&(!checkPawnMate||!isPawnDropMate(s,m)))}
function positionKey(s){const board=s.board.flat().map(p=>p?`${p.side[0]}${p.promoted?1:0}${p.type}`:'_').join('');const hand=side=>[...s.hands[side]].sort().join('');return`${board}|${hand('sente')}|${hand('gote')}|${s.turn}`}
function makeRecord(s,mover=null){return{key:positionKey(s),mover,gaveCheck:mover?inCheck(s,s.turn):false}}
function repetitionResult(log){if(log.length<7)return null;const current=log[log.length-1].key,at=[];for(let i=0;i<log.length;i++)if(log[i].key===current)at.push(i);if(at.length<4)return null;const cycle=log.slice(at[at.length-4]+1);for(const side of ['sente','gote']){const moves=cycle.filter(x=>x.mover===side);if(moves.length&&moves.every(x=>x.gaveCheck))return{winner:other(side),reason:'perpetual-check'}}return{winner:'draw',reason:'sennichite'}}
function snapshot(){return{state:clone(state),records:records.map(x=>({...x}))}}
function pushRecord(mover){records.push(makeRecord(state,mover))}
function key(m){return`${m.drop?'D'+m.type:m.from.join('')}-${m.to.join('')}-${m.promote?1:0}`}
function material(s,side){let sum=0;for(const row of s.board)for(const p of row)if(p)sum+=(p.side===side?1:-1)*(V[p.type]+(p.promoted?2:0));for(const x of s.hands[side])sum+=V[x];for(const x of s.hands[other(side)])sum-=V[x];return sum}
function dangerLoss(s,side){let loss=0;for(let r=0;r<9;r++)for(let c=0;c<9;c++){const p=s.board[r][c];if(p?.side===side&&p.type!=='K'&&attacked(s,r,c,other(side)))loss+=V[p.type]+(p.promoted?2:0)}return loss}
function positional(s,side){let x=0;for(let r=0;r<9;r++)for(let c=0;c<9;c++){const p=s.board[r][c];if(p?.side!==side)continue;x+=(4-Math.abs(4-c))*.12;if(p.type!=='K')x+=(side==='gote'?r:8-r)*.05}return x}
function evaluateMove(s,m,randomness=.8){const beforeDanger=dangerLoss(s,m.side),cap=s.board[m.to[0]][m.to[1]],n=apply(s,m),afterDanger=dangerLoss(n,m.side);let score=material(n,m.side)*20+positional(n,m.side)+(randomness?Math.random()*randomness:0);score+=(beforeDanger-afterDanger)*95;if(cap)score+=V[cap.type]*125;if(m.promote)score+=(V[s.board[m.from[0]][m.from[1]].type]||1)*16;if(attacked(n,m.to[0],m.to[1],other(m.side))){const own=n.board[m.to[0]][m.to[1]];score-=V[own.type]*105}if(inCheck(n,other(m.side)))score+=32;return score}
function staticEval(s,root='gote'){const foe=other(root);let score=material(s,root)*24+positional(s,root)-positional(s,foe);score-=dangerLoss(s,root)*68;score+=dangerLoss(s,foe)*54;if(inCheck(s,foe))score+=28;if(inCheck(s,root))score-=36;return score}
function kingSafety(s,side){let kr=-1,kc=-1;for(let r=0;r<9;r++)for(let c=0;c<9;c++)if(s.board[r][c]?.side===side&&s.board[r][c].type==='K'){kr=r;kc=c}if(kr<0)return-10000;let defenders=0,hostile=0,escapes=0;for(const [dr,dc] of dirs.K){const r=kr+dr,c=kc+dc;if(!inside(r,c))continue;const p=s.board[r][c];if(p?.side===side&&(p.type==='G'||p.type==='S'||p.type==='K'))defenders++;if(attacked(s,r,c,other(side)))hostile++;else if(!p||p.side!==side)escapes++}return defenders*5+escapes*1.5-hostile*7}
function strongEval(s,root='gote'){const foe=other(root);return material(s,root)*100+positional(s,root)*3-positional(s,foe)*3+(kingSafety(s,root)-kingSafety(s,foe))*4-(dangerLoss(s,root)*32)+(dangerLoss(s,foe)*27)}
function moveOrderScore(s,m,root,preferred){if(preferred&&key(m)===preferred)return 1e9;const cap=s.board[m.to[0]][m.to[1]],mover=m.drop?{type:m.type}:s.board[m.from[0]][m.from[1]];let score=0;if(cap)score+=V[cap.type]*1000-(V[mover.type]||1)*35;if(m.promote)score+=(V[mover.type]||1)*180;const n=apply(s,m);if(inCheck(n,other(m.side)))score+=450;if(attacked(n,m.to[0],m.to[1],other(m.side)))score-=(V[mover.type]||1)*90;if(attacked(n,m.to[0],m.to[1],m.side))score+=(V[mover.type]||1)*18;return score}
function orderList(s,moves,root,preferred=null){return moves.sort((a,b)=>moveOrderScore(s,b,root,preferred)-moveOrderScore(s,a,root,preferred))}
function ordered(s,side,root,limit=Infinity,preferred=null){const moves=orderList(s,legalMoves(s,side),root,preferred);return Number.isFinite(limit)?moves.slice(0,limit):moves}
function minimax(s,depth,alpha,beta,root,beam,deadline){searchNodes++;if(depth<=0||performance.now()>=deadline)return staticEval(s,root);const moves=ordered(s,s.turn,root,beam);if(!moves.length)return s.turn===root?-100000-depth:100000+depth;if(s.turn===root){let value=-Infinity;for(const m of moves){value=Math.max(value,minimax(apply(s,m),depth-1,alpha,beta,root,beam,deadline));alpha=Math.max(alpha,value);if(beta<=alpha||performance.now()>=deadline)break}return value}let value=Infinity;for(const m of moves){value=Math.min(value,minimax(apply(s,m),depth-1,alpha,beta,root,beam,deadline));beta=Math.min(beta,value);if(beta<=alpha||performance.now()>=deadline)break}return value}
function checkDeadline(deadline){if(performance.now()>=deadline)throw SEARCH_TIMEOUT}
function quiescence(s,alpha,beta,root,deadline,depth){checkDeadline(deadline);searchNodes++;const maximizing=s.turn===root,checked=inCheck(s,s.turn),moves=legalMoves(s,s.turn);if(!moves.length)return maximizing?-MATE_SCORE-depth:MATE_SCORE+depth;const stand=strongEval(s,root);if(depth<0||depth===0&&!checked)return stand;let value=checked?(maximizing?-Infinity:Infinity):stand;if(!checked){if(maximizing){if(value>=beta)return value;alpha=Math.max(alpha,value)}else{if(value<=alpha)return value;beta=Math.min(beta,value)}}const tactical=orderList(s,checked?moves:moves.filter(m=>{const cap=s.board[m.to[0]][m.to[1]];if(cap||m.promote)return true;return inCheck(apply(s,m),other(m.side))}),root);for(const m of tactical){const score=quiescence(apply(s,m),alpha,beta,root,deadline,depth-1);if(maximizing){value=Math.max(value,score);alpha=Math.max(alpha,value)}else{value=Math.min(value,score);beta=Math.min(beta,value)}if(alpha>=beta)break}return value}
function strongSearch(s,depth,alpha,beta,root,deadline,cfg,extensionsLeft=cfg.extensions){checkDeadline(deadline);searchNodes++;const checked=inCheck(s,s.turn);let effectiveDepth=depth,nextExtensions=extensionsLeft;if(checked&&extensionsLeft>0){effectiveDepth++;nextExtensions--}if(effectiveDepth<=0)return quiescence(s,alpha,beta,root,deadline,cfg.qDepth);const hash=positionKey(s),cached=transpositionTable.get(hash),originalAlpha=alpha,originalBeta=beta;if(cached&&cached.depth>=effectiveDepth){if(cached.flag==='exact')return cached.score;if(cached.flag==='lower')alpha=Math.max(alpha,cached.score);if(cached.flag==='upper')beta=Math.min(beta,cached.score);if(alpha>=beta)return cached.score}const moves=ordered(s,s.turn,root,Infinity,cached?.bestMove);if(!moves.length)return s.turn===root?-MATE_SCORE-effectiveDepth:MATE_SCORE+effectiveDepth;const maximizing=s.turn===root;let value=maximizing?-Infinity:Infinity,bestMove=null,first=true;for(let moveIndex=0;moveIndex<moves.length;moveIndex++){checkDeadline(deadline);const m=moves[moveIndex],child=apply(s,m),quiet=!s.board[m.to[0]][m.to[1]]&&!m.promote&&!inCheck(child,other(m.side));const reduction=cfg.lmr&&effectiveDepth>=3&&moveIndex>=4&&!checked&&quiet?Math.min(cfg.lmr,effectiveDepth-2):0;let score;if(first)score=strongSearch(child,effectiveDepth-1,alpha,beta,root,deadline,cfg,nextExtensions);else if(reduction){score=strongSearch(child,effectiveDepth-1-reduction,alpha,beta,root,deadline,cfg,nextExtensions);if(maximizing?score>alpha:score<beta)score=strongSearch(child,effectiveDepth-1,alpha,beta,root,deadline,cfg,nextExtensions)}else if(maximizing){score=strongSearch(child,effectiveDepth-1,alpha,alpha+1,root,deadline,cfg,nextExtensions);if(score>alpha&&score<beta)score=strongSearch(child,effectiveDepth-1,alpha,beta,root,deadline,cfg,nextExtensions)}else{score=strongSearch(child,effectiveDepth-1,beta-1,beta,root,deadline,cfg,nextExtensions);if(score<beta&&score>alpha)score=strongSearch(child,effectiveDepth-1,alpha,beta,root,deadline,cfg,nextExtensions)}first=false;if(maximizing){if(score>value){value=score;bestMove=m}alpha=Math.max(alpha,value)}else{if(score<value){value=score;bestMove=m}beta=Math.min(beta,value)}if(alpha>=beta)break}let flag='exact';if(value<=originalAlpha)flag='upper';else if(value>=originalBeta)flag='lower';if(transpositionTable.size>60000)transpositionTable.clear();transpositionTable.set(hash,{depth:effectiveDepth,score:value,flag,bestMove:bestMove&&key(bestMove)});return value}
function forcedMate(s,attacker,depth,deadline){checkDeadline(deadline);const moves=legalMoves(s,s.turn);if(!moves.length)return s.turn!==attacker&&inCheck(s,s.turn);if(depth<=0)return false;if(s.turn===attacker){for(const m of moves){const n=apply(s,m);if(inCheck(n,other(attacker))&&forcedMate(n,attacker,depth-1,deadline))return true}return false}for(const m of moves)if(!forcedMate(apply(s,m),attacker,depth-1,deadline))return false;return true}
function findMateMove(s,cfg,deadline){const mateDeadline=Math.min(deadline,performance.now()+cfg.mateTime);for(const m of ordered(s,'gote','gote')){checkDeadline(mateDeadline);const n=apply(s,m);if(inCheck(n,'sente')&&forcedMate(n,'gote',cfg.mateDepth-1,mateDeadline))return m}return null}
function searchRoot(s,depth,deadline,cfg,preferred){let best=null,bestScore=-Infinity,alpha=-Infinity;for(const m of ordered(s,'gote','gote',Infinity,preferred)){checkDeadline(deadline);const score=strongSearch(apply(s,m),depth-1,alpha,Infinity,'gote',deadline,cfg);if(score>bestScore){bestScore=score;best=m}alpha=Math.max(alpha,bestScore)}return best}
function chooseStrongAI(s,cfg){searchNodes=0;completedDepth=0;transpositionTable.clear();const deadline=performance.now()+cfg.time,moves=legalMoves(s,'gote');if(!moves.length)return null;let best=ordered(s,'gote','gote')[0];if(cfg.mateDepth)try{const mate=findMateMove(s,cfg,deadline);if(mate){completedDepth=cfg.mateDepth;return mate}}catch(error){if(error!==SEARCH_TIMEOUT)throw error}for(let depth=1;depth<=cfg.maxDepth;depth++){try{const found=searchRoot(s,depth,deadline,cfg,best&&key(best));if(found){best=found;completedDepth=depth}}catch(error){if(error===SEARCH_TIMEOUT)break;throw error}}return best}
function chooseAI(s){const cfg=LEVELS[level];if(cfg.engine==='strong')return chooseStrongAI(s,cfg);const deadline=performance.now()+cfg.time;searchNodes=0;completedDepth=cfg.depth;const moves=legalMoves(s,'gote').sort((a,b)=>evaluateMove(s,b,cfg.randomness)-evaluateMove(s,a,cfg.randomness)).slice(0,cfg.root);if(!moves.length)return null;let best=moves[0],bestScore=-Infinity;for(const m of moves){const n=apply(s,m),score=cfg.depth===1?evaluateMove(s,m,cfg.randomness):minimax(n,cfg.depth-1,-Infinity,Infinity,'gote',cfg.beam,deadline)+evaluateMove(s,m,cfg.randomness)*.18;if(score>bestScore){bestScore=score;best=m}if(performance.now()>=deadline&&searchNodes>0)break}return best}
function stateToSFEN(s){const codes={P:'P',L:'L',N:'N',S:'S',G:'G',B:'B',R:'R',K:'K'};const rows=s.board.map(row=>{let out='',empty=0;for(const p of row){if(!p){empty++;continue}if(empty){out+=empty;empty=0}let code=(p.promoted?'+':'')+codes[p.type];if(p.side==='gote')code=code.replace(/[A-Z]/,x=>x.toLowerCase());out+=code}if(empty)out+=empty;return out});const hand=[];for(const side of ['sente','gote'])for(const type of ['R','B','G','S','N','L','P']){const count=s.hands[side].filter(x=>x===type).length;if(!count)continue;let code=codes[type];if(side==='gote')code=code.toLowerCase();hand.push(`${count>1?count:''}${code}`)}return`${rows.join('/')} ${s.turn==='sente'?'b':'w'} ${hand.join('')||'-'} ${Math.max(1,s.move+1)}`}
function parseUSIMove(usi,s){if(!usi)return null;if(usi==='resign'||usi==='win')return{special:usi};let candidate;if(usi[1]==='*'){const types={P:'P',L:'L',N:'N',S:'S',G:'G',B:'B',R:'R'},file=Number(usi[2]),rank=usi.charCodeAt(3)-97;candidate={side:s.turn,drop:true,type:types[usi[0]],to:[rank,9-file]}}else{const fromFile=Number(usi[0]),fromRank=usi.charCodeAt(1)-97,toFile=Number(usi[2]),toRank=usi.charCodeAt(3)-97;candidate={side:s.turn,from:[fromRank,9-fromFile],to:[toRank,9-toFile],promote:usi[4]==='+'}}if(!candidate.type&&!candidate.from)return null;return legalMoves(s,s.turn).find(m=>key(m)===key(candidate))||null}
function disposeHeroWorker(reason='勇者エンジンを停止しました'){const rejectReady=heroReadyReject;if(heroWorker)heroWorker.terminate();heroWorker=null;heroReady=null;heroReadyResolve=null;heroReadyReject=null;rejectReady?.(new Error(reason));for(const pending of heroPending.values()){clearTimeout(pending.timer);pending.reject(new Error(reason))}heroPending.clear()}
function ensureHeroWorker(){if(heroWorker)return heroWorker;heroWorker=new Worker(new URL('engine/hero-worker.js',document.baseURI));heroReady=new Promise((resolve,reject)=>{heroReadyResolve=resolve;heroReadyReject=reject});heroWorker.onmessage=event=>{const msg=event.data||{};if(msg.type==='ready'){heroReadyResolve?.();heroReadyResolve=null;heroReadyReject=null;return}if(msg.type==='bestmove'){const pending=heroPending.get(msg.id);if(!pending)return;clearTimeout(pending.timer);heroPending.delete(msg.id);pending.resolve({bestmove:msg.bestmove,info:msg.info});return}if(msg.type==='error'){const pending=heroPending.get(msg.id);if(pending){clearTimeout(pending.timer);heroPending.delete(msg.id);pending.reject(new Error(msg.error||'勇者エンジンエラー'))}else heroReadyReject?.(new Error(msg.error||'勇者エンジン初期化エラー'))}};heroWorker.onerror=event=>disposeHeroWorker(event.message||'勇者エンジンの読込に失敗しました');heroWorker.postMessage({type:'init'});return heroWorker}
function warmHeroEngine(){try{ensureHeroWorker()}catch(error){console.warn(error)}}
async function chooseHeroAI(s,cfg){const worker=ensureHeroWorker();await heroReady;const id=++heroSequence,result=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>{heroPending.delete(id);disposeHeroWorker('勇者エンジンが応答しません');reject(new Error('勇者エンジンが応答しません'))},20000);heroPending.set(id,{resolve,reject,timer});worker.postMessage({type:'search',id,gameId,sfen:stateToSFEN(s),movetime:cfg.time})});return parseUSIMove(result.bestmove,s)}
function textPiece(p){return p.promoted?(PN[p.type]||N[p.type]):N[p.type]}
function resultText(){if(state.winner==='draw')return state.endReason==='sennichite'?'千日手です。引き分けになりました':'500手に達したため持将棋です';if(state.winner){const base=state.winner==='sente'?'あなたの勝ちです':'コンピューターの勝ちです';return state.endReason==='perpetual-check'?`${base}（連続王手の千日手）`:base}return state.turn==='sente'?(inCheck(state,'sente')?'王手です。王手を回避してください':'あなたの手番です'):'コンピューターが考えています'}
function render(){boardEl.replaceChildren();const targets=new Map(legalTargets.map(m=>[m.to.join(','),m]));state.board.forEach((row,r)=>row.forEach((p,c)=>{const b=document.createElement('button'),k=`${r},${c}`,target=targets.get(k);b.className='square';if(selected?.kind==='board'&&selected.r===r&&selected.c===c)b.classList.add('selected');if(target)b.classList.add(p?'capture':'legal');if(state.last&&(state.last.to.join(',')===k||state.last.from?.join(',')===k))b.classList.add('last');b.dataset.r=r;b.dataset.c=c;b.setAttribute('role','gridcell');b.setAttribute('aria-label',`${9-c}筋${r+1}段${p?(p.side==='sente'?'先手':'後手')+textPiece(p):'空き'}`);if(p){const span=document.createElement('span'),code=(p.promoted?'+':'')+p.type;span.className=`piece ${p.side}${p.promoted?' promoted':''}`;span.innerHTML=`<i class="character ${SPRITE[code]||SPRITE[p.type]}"></i><b class="piece-label">${textPiece(p)}</b>`;b.append(span)}b.addEventListener('click',onSquare);boardEl.append(b)}));renderHand('sente');renderHand('gote');statusEl.textContent=resultText()}
function renderHand(side){const el=$(`#${side}-hand`);el.replaceChildren();const counts={};state.hands[side].forEach(x=>counts[x]=(counts[x]||0)+1);for(const type of Object.keys(counts).sort((a,b)=>V[b]-V[a])){const b=document.createElement('button');b.className='hand-piece';if(selected?.kind==='hand'&&selected.type===type&&side==='sente')b.classList.add('selected');b.innerHTML=`<i class="hand-character character ${SPRITE[type]}"></i><span>${N[type]}<small class="count">×${counts[type]}</small></span>`;b.disabled=side!=='sente'||state.turn!=='sente'||busy||!!state.winner;b.addEventListener('click',()=>selectHand(type));el.append(b)}}
function selectHand(type){if(busy||state.turn!=='sente'||state.winner)return;selected={kind:'hand',type};legalTargets=legalMoves(state,'sente').filter(m=>m.drop&&m.type===type);render()}
function onSquare(e){if(busy||state.turn!=='sente'||state.winner)return;const r=+e.currentTarget.dataset.r,c=+e.currentTarget.dataset.c,match=legalTargets.filter(m=>m.to[0]===r&&m.to[1]===c);if(match.length){commitHuman(match);return}const p=state.board[r][c];if(p?.side==='sente'){selected={kind:'board',r,c};legalTargets=legalMoves(state,'sente').filter(m=>!m.drop&&m.from[0]===r&&m.from[1]===c);render()}else{selected=null;legalTargets=[];render()}}
async function commitHuman(options){let m=options.find(x=>!x.promote)||options[0];if(options.some(x=>x.promote)&&options.some(x=>!x.promote)){promotion.showModal();const answer=await new Promise(resolve=>promotion.addEventListener('close',()=>resolve(promotion.returnValue),{once:true}));m=options.find(x=>x.promote===(answer==='promote'))||m}history.push(snapshot());state=apply(state,m);pushRecord(m.side);selected=null;legalTargets=[];finishOrAI()}
function detectEnd(){const moves=legalMoves(state,state.turn);if(!moves.length){state.winner=other(state.turn);state.endReason='no-legal-moves';return true}const repeated=repetitionResult(records);if(repeated){state.winner=repeated.winner;state.endReason=repeated.reason;return true}if(state.move>=500&&!inCheck(state,state.turn)){state.winner='draw';state.endReason='max-moves';return true}return false}
async function finishOrAI(){render();if(detectEnd()){render();return}if(state.turn==='gote'){busy=true;const pendingGame=gameId,cfg=LEVELS[level];thinkingEl.textContent=cfg.engine==='yaneuraou'?'勇者エンジンを起動・思考中…':cfg.engine==='strong'?`${cfg.name}・反復深化で思考中…`:`${cfg.name}・${cfg.depth}手読みで思考中…`;render();await new Promise(r=>setTimeout(r,60));if(pendingGame!==gameId)return;const start=performance.now();let m,usedFallback=false;try{m=cfg.engine==='yaneuraou'?await chooseHeroAI(state,cfg):chooseAI(state)}catch(error){if(pendingGame!==gameId)return;console.warn(error);usedFallback=true;m=chooseStrongAI(state,LEVELS.master)}if(pendingGame!==gameId)return;const elapsed=Math.round(performance.now()-start);if(m?.special==='resign'){state.winner='sente';state.endReason='engine-resign';thinkingEl.textContent='勇者：投了';busy=false;render();return}if(m?.special==='win'){state.winner='gote';state.endReason='entering-king';thinkingEl.textContent='勇者：入玉宣言';busy=false;render();return}if(m){history.push(snapshot());state=apply(state,m);pushRecord(m.side)}thinkingEl.textContent=cfg.engine==='yaneuraou'&&!usedFallback?`勇者・YaneuraOu：${elapsed}ms`:usedFallback?`勇者互換・猛者AI：${elapsed}ms・深度${completedDepth}`:cfg.engine==='strong'?`${cfg.name}：${elapsed}ms・深度${completedDepth}・${searchNodes.toLocaleString()}局面`:`${cfg.name}：${elapsed}ms・${searchNodes.toLocaleString()}局面`;busy=false;if(detectEnd())render();else render()}}
function reset(){gameId++;if(heroPending.size)disposeHeroWorker('新しい対局を開始しました');state=fresh();selected=null;legalTargets=[];history=[];records=[makeRecord(state)];busy=false;thinkingEl.textContent='';render()}
function setLevel(next){if(busy||!LEVELS[next])return;level=next;document.querySelectorAll('[data-level]').forEach(b=>b.classList.toggle('active',b.dataset.level===level));thinkingEl.textContent='';if(level==='hero')warmHeroEngine()}
$('#new-game').addEventListener('click',reset);$('#undo').addEventListener('click',()=>{if(busy||!history.length)return;while(history.length){const saved=history.pop();state=saved.state;records=saved.records;if(state.turn==='sente')break}selected=null;legalTargets=[];render()});document.querySelectorAll('[data-level]').forEach(b=>b.addEventListener('click',()=>setLevel(b.dataset.level)));reset();setLevel(level);
document.addEventListener('touchmove',e=>{if(e.touches?.length>1)e.preventDefault()},{passive:false});document.addEventListener('gesturestart',e=>e.preventDefault(),{passive:false});document.addEventListener('gesturechange',e=>e.preventDefault(),{passive:false});
